name: Bump Helm Chart Version

on:
  repository_dispatch:
    types: [bump-chart]

jobs:
  bump-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3
        id: app-token
        with:
          client-id: ${{ secrets.COMMIT_BOT_CLIENT_ID }}
          private-key: ${{ secrets.COMMIT_BOT_PRIVATE_KEY }}
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Bump chart version
        id: bump_chart
        run: |
          CHART_NAME=${{ github.event.client_payload.chart_name }}
          NEW_APP_VERSION=${{ github.event.client_payload.chart_version }}
          CHART_PATH="charts/$CHART_NAME/Chart.yaml"

          echo "Processing chart: $CHART_NAME with new version: $NEW_APP_VERSION"

          CURRENT_CHART_VERSION=$(grep '^version:' $CHART_PATH | awk '{print $2}')
          NEW_CHART_VERSION=$(echo $CURRENT_CHART_VERSION | awk -F . '{$NF = $NF + 1;} 1' OFS=.)

          echo "Current chart version: $CURRENT_CHART_VERSION"
          echo "New chart version: $NEW_CHART_VERSION"

          # Without "v" prefix for output
          NEW_CHART_VERSION_CLEAN=${NEW_CHART_VERSION#v}
          NEW_APP_VERSION_CLEAN=${NEW_APP_VERSION#v}

          sed -i "s/^version: .*/version: $NEW_CHART_VERSION_CLEAN/" $CHART_PATH
          sed -i "s/^appVersion: .*/appVersion: $NEW_APP_VERSION_CLEAN/" $CHART_PATH

          echo "CHART_VERSION=$NEW_CHART_VERSION" >> $GITHUB_OUTPUT

      - name: Create PR
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: "Bump chart version for ${{ github.event.client_payload.chart_name }} to ${{ steps.bump_chart.outputs.CHART_VERSION }}"
          branch: chore/bump-chart-version-${{ github.event.client_payload.chart_name }}-${{ steps.bump_chart.outputs.CHART_VERSION }}
          title: "Bump ${{ github.event.client_payload.chart_name }}: Chart ${{ steps.bump_chart.outputs.CHART_VERSION }} App ${{ github.event.client_payload.chart_version }}"
          body: |
            Automated version bump:
            - **Chart Version**: ${{ steps.bump_chart.outputs.CHART_VERSION }}
            - **App Version**: ${{ github.event.client_payload.chart_version }}
          base: main
          sign-commits: true
          labels: bump-chart
