name: Helm Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release Helm Charts
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3
        id: app-token
        with:
          client-id: ${{ secrets.COMMIT_BOT_CLIENT_ID }}
          private-key: ${{ secrets.COMMIT_BOT_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config user.name "profidev-commit-bot[bot]"
          git config user.email "profidev-commit-bot[bot]@users.noreply.github.com"
      - name: Run chart-releaser job
        uses: helm/chart-releaser-action@v1
        env:
          CR_TOKEN: "${{ steps.app-token.outputs.token }}"
